### model
model_name_or_path: models/Qwen/Qwen2___5-0___5B-Instruct
adapter_name_or_path: saves/Qwen2.5-0.5B/lora/sft
template: qwen2_5
trust_remote_code: true

### export
export_dir: output/qwen2.5-0.5b-merged
export_size: 2
export_device: cpu
export_legacy_format: false



